[package]
name = "hl2-lib"
version = "1.0.0"
edition = "2021"
description = "a library for highlighting streams of text via regex."
license = "MIT"

[lib]

[dev-dependencies]
tempfile = "3.14.0"

[dependencies]
clap = { version = "4.5.23", features = ["derive"] }
colored = "2.1.0"
regex = "1.11.1"
