[package]
name = "hl-rs"
version = "0.1.0"
edition = "2021"

[lib]

[[bin]]
name = "hl"
path = "src/main.rs"

[dev-dependencies]
tempfile = "3.14.0"

[dependencies]
colored = "2.1.0"
regex = "1.11.1"
